version: "3.8"
services:
  web:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    env_file:
      - .env
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    networks:
      - arthur

networks:
  arthur:
    name: arthur
    external: true
    driver: bridge

